spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaozg/config-repo-demo/    # 配置git仓库的地址
          #search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          #username: username                                        # git仓库的账号
          #password: password                                    # git仓库的密码
server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:2002/eureka/   # 注册中心eurka地址

